220809 add footer
starrynightlabs/web pull request #13
Opened 2022-08-09 10:05 UTC by ye-ha

## Changes
- Update copyright text and style
- Add logo and copyright in footer
- Add Social Media Buttons 

<img width="359" alt="image" src="https://user-images.githubusercontent.com/60090790/183622251-67893415-1b79-41fe-bd5c-7a6d6c81a47a.png">

2022-08-09 10:07 UTC, ye-ha commented
just added buttons, I have to link it.

2022-08-09 11:32 UTC, sebatyler requested changes
Review is done. Please check comments.

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +          const Divider(color: Color(0xff838383), height: 24.0, thickness: 1.0),
endIndent: 16.0 넣어주어야 할 것 같네요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +          const SizedBox(height: 32.0),
46.0 이 맞는것 같네요. 피그마에도 커멘트 했어요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +          const SizedBox(height: 32.0),
여기도요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +      padding: const EdgeInsets.all(0.0),
기본이 0 이 아니어서 0.0 으로 넣어주신거죠?

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +Widget getSocialMediaButton(title) {
title 대신 image_path 정도로 하는게 더 명확할 것 같네요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +      '© 2022 All Rights Reserved. Starry Night Labs Pte. Ltd.\nPrivacy Policy and Terms Of Use.',
Privacy Policy, Terms Of Use 각각이 링크로 들어가야 하긴 합니다.
윗줄에 TODO: 주석 달아주시면 좋을것 같네요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +      getSocialMediaButton('images/mail.png')
메일의 경우는 onPressed 에서 contact@snlabs.io 를 launchUrl 함수로 호출해야 합니다.
contactEmail 함수 참고하면 되고요
이메일 혹은 링크를 getSocialMediaButton의 2번째 인자로 전달하고 onPressed 를 구현하면 어떨까 싶네요

107행의 contactEmail 넣어주는 부분은 이번에 삭제해버리는게 좋을 것 같네요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +          const Text('Launching soon to\nApple Store & Google Play Store.',
여기도 Apple Store, Google Play Store 에는 추후 링크가 들어가야 하기 때문에
윗줄에 TODO: 주석을 달아두면 좋을 것 같네요

2022-08-09 11:32 UTC, sebatyler commented on lib/main.dart
> +          Image.asset('images/large_logo_white.png', width: 127, height: 43),
여기에도 FilterQuality.high 넣어주는게 어떨까요?

2022-08-09 11:54 UTC, sebatyler commented on lib/main.dart
> +      getSocialMediaButton('images/twitter.png'),
트위터 링크 나왔네요
https://twitter.com/StarryNightFndn

2022-08-09 11:56 UTC, sebatyler commented on lib/main.dart
> +          const SizedBox(height: 32.0),
위아래 모두 32.0 이 맞네요 ㅎㅎ

2022-08-09 11:59 UTC, sebatyler commented on lib/main.dart
> +          const SizedBox(height: 32.0),
32가 맞아서 resolve 합니다.

2022-08-10 01:04 UTC, ye-ha commented on lib/main.dart
> +      padding: const EdgeInsets.all(0.0),
IconButton의 padding 기본값이 8.0이라서 0.0으로 주었어요.
![image](https://user-images.githubusercontent.com/60090790/183787804-e2fb05e9-f82c-427e-b712-6632a478dc0f.png)

그래서 0.0 적용을 하지 않으면 패딩만큼 눌려서 나와요. 
![image](https://user-images.githubusercontent.com/60090790/183787862-496cd2c5-1efb-4f91-af38-96f397808dd6.png)

2022-08-10 01:04 UTC, ye-ha commented on lib/main.dart
> +          const Divider(color: Color(0xff838383), height: 24.0, thickness: 1.0),
앗, 추가했습니다

2022-08-10 01:08 UTC, ye-ha commented on lib/main.dart
> +Widget getSocialMediaButton(title) {
imagePath 로 변경했습니다

2022-08-10 01:20 UTC, ye-ha commented on lib/main.dart
> +          Image.asset('images/large_logo_white.png', width: 127, height: 43),
적용했습니다

2022-08-10 01:35 UTC, ye-ha commented on lib/main.dart
> +      '© 2022 All Rights Reserved. Starry Night Labs Pte. Ltd.\nPrivacy Policy and Terms Of Use.',
네, `TODO: create hyperlink to Privacy Policy, Terms Of Use.` 로 달았습니다

2022-08-10 01:41 UTC, ye-ha commented on lib/main.dart
> +          const Text('Launching soon to\nApple Store & Google Play Store.',
`TODO: create hyperlink to App Store, Play Store.`로 주석 남겼습니다. 
피그마에도 코멘트 남겼는데, App Store가 정식 명칭이라 'Apple App Store'로 바꾸는게 어떨까요?

2022-08-10 01:46 UTC, sebatyler commented on lib/main.dart
> +      padding: const EdgeInsets.all(0.0),
네 설명 감사합니다.

2022-08-10 01:47 UTC, sebatyler commented on lib/main.dart
> +          const Text('Launching soon to\nApple Store & Google Play Store.',
아하 네. 좋네요

2022-08-10 02:44 UTC, sebatyler approved these changes
Nice work! As we discussed on scrum, I'll attach email and twitter link afterwards.

2022-08-10 02:57 UTC, ye-ha commented
Thank for the approval!

2022-08-10 02:57 UTC, merged