Apply animation effets
starrynightlabs/web pull request #30
Opened 2022-08-19 08:57 UTC by ye-ha

## Changes
- Apply animation effets for mobile website 
   - (UI elements positions need to be discussed.)

2022-08-19 08:57 UTC, sebatyler commented
Task linked: [CU-2xx2rn2 Add animations to mobile website](https://app.clickup.com/t/2xx2rn2)

2022-08-19 09:03 UTC, sebatyler commented on lib/main.dart
> +    _controller.dispose;
() 빠진 것 같네요

2022-08-19 09:03 UTC, sebatyler commented on lib/main.dart
> +    isSpecialExperienceShown = false;
bool 변수 모두 기본값이 false 인데 추가로 값을 넣어주어야 하나요?

2022-08-21 02:54 UTC, ye-ha commented on lib/main.dart
> +    isSpecialExperienceShown = false;
말씀하신 내용이 맞습니다. 미처 지우지 못했습니다.😓 55번 print와 함께 지웠습니다.

2022-08-21 03:08 UTC, ye-ha commented on lib/main.dart
> +    _controller.dispose;
앗 ()가 빠졌군요. 감사합니다!

2022-08-22 02:24 UTC, sebatyler commented
Confirmed the 2 new commits after review!

2022-08-22 02:39 UTC, ye-ha commented
😁 I'll add commits after discussing!

2022-08-25 09:08 UTC, ye-ha commented
논의했던 내용을 바탕으로 수정한 내용입니다. 
- https://github.com/starrynightlabs/web/pull/30/commits/417b4a4ed56b7f87b6ad06bccba3a41ef5ab56d3 HowToPlay 내부의 파트들이 애니메이션 동작 여부를 각각 체크하도록 수정
- https://github.com/starrynightlabs/web/pull/30/commits/03b7baada08a9190796e089cda16a822d1632655 HowToPlay 내부의 파트에 적용된 decoration이 위에서 아래로 내려오도록 수정
- https://github.com/starrynightlabs/web/pull/30/commits/03b7baada08a9190796e089cda16a822d1632655 아래에서 위로 올라오는 애니메이션이 제대로 적용되도록 수정
  - Align -> Position으로 변경했습니다. 위젯들이 위아래로 움직일 여유 공간이 없어서 위치 이동 애니메이션이 보이지 않았던 것으로 추정하고 있습니다. 
  - 화면을 구성하는 위젯들을 모두 Stack 내부로 옮겼습니다. Stack은 크기가 정해져있는 위젯으로 감싸주었습니다. BoxDecoration이 필요하면 Container, 필요하지 않으면 SizedBox을 사용했습니다.
  - Stack 내부의 위젯들이 어디에 그려져야 하는지 `fooTop`을 통해 지정해주었습니다. 위치 설정을 위한 여백 SizedBox가 불필요해져 제거했습니다. 
- https://github.com/starrynightlabs/web/pull/30/commits/a3d92cddf99d724c91d4b05d975eb71d4d8d8cca 첫 페이지는 자동으로 애니메이션이 동작하도록 변경
  - 첫 페이지의 애니메이션이 자동으로 작동되게 하기 위해 `title`, `description`, `image`를 담당하는 3개의 AnimationController를 생성했습니다.
  - 기존에 사용하던 ImplicitlyAnimatedWidget(AnimatedPosition, AnimatedOpacity)에 조건을 주어 세 개의 화면 요소를 순차적으로 작동시키기가 까다로워 AnimatedWidget인 FadeTransition, SlideTransition로 변경했습니다. 
  - Timer로 텀을 두고 `AnimationController.forward()`로 애니메이션의 시작시점을 정해주었습니다. 
  - 첫 페이지의 애니메이션들은 `AnimationController.forward()`를 호출하지 않으면 동작되지 않기에 애니메이션 동작 여부를 확인하는 `isWeMakeStarsShown`은 삭제했습니다.

2022-08-29 09:57 UTC, sebatyler requested changes
Sorry for too late review. Please check comments!

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +          ? Positioned(top: imageTop, child: image)
스크롤을 일부만 내린 상태에서는 player_cards.png 파일의 왼쪽 부분만 보여지는데 스크롤을 다 내려서 isHowToPlayTwoShown=true 가 되면 가운데 정렬형태로 되어버리네요. 의도한 부분일까요?
<img width="503" alt="image" src="https://user-images.githubusercontent.com/646368/187168767-836bb4b6-b2e9-4b8b-9178-67c568a0a729.png">

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +  late final AnimationController _imageAnimationController;
bool 변수들과 AnimationController 객체들을 아예 map 으로 관리하는건 어떨까요?
빈 map 으로 초기화하면 late final 도 필요없어지고 initState 에서 루프 돌면서 일괄적으로 세팅하는 코드도 단순해질 것 같거든요
예를 들면 이런식으로요. 단, 코드 수정이 여기저기 필요해보여서 애니메이션 적용 이후에 리팩토링할때 적용해도 좋을 것 같네요. 예하님이 판단해서 진행해주세요.

```dart
    Map<String, bool> partShown = {};
    Map<String, AnimationController> animationController = {};
    
    @override
    void initState() {
        for (var k in ['whatIsNyxs', 'howToPlayTitle', ...]) {
            partShown[k] = false;
        }
        for (var k in ['title', 'description', 'image']) {
            animationController[k] = AnimationController(
                 duration: const Duration(milliseconds: 500),
                 vsync: this,
            );
        }


    }
```

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +    required widget,
widget은 함수 이름만 보아도 전달하는게 당연해 보여서 optional argument 대신에 첫번째 인자로 항상 넣어주게 하는게 어떨까요?

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +      top: pixels <= startingPoint
3항 연산이 여러줄인데다가 최대 2번이나 하게 되어서 복잡해보이네요
top을 위에서 먼저 계산하도록 빼거나 reverse 값에 따른 부분을 위에서 먼저 계산해둬서 단순해보이게 해주면 좋을 것 같네요

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +                  widget: getTitleText(suffix: 'NYXS'),
getTitleText 같은걸 2번 호출하고 있어서 변수로 빼주는게 좋겠네요

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +          ...howToPlayPartOne,
... 을 반복하고 있어서 + 로 붙이는게 조금 더 보기 편해지지 않을까 싶네요
```dart
     childern: [
           ...
     ] + howToPlayPartOne + howToPlayPartTwo + howToPlayPartThree;
```

2022-08-29 09:57 UTC, sebatyler commented on lib/main.dart
> +                  widget: getDescriptionText(starDescription),
773행부터 여기까지 중복되는 함수 호출이 많네요. 변수로 다 빼주세요

2022-08-30 01:48 UTC, ye-ha commented on lib/main.dart
> +    required widget,
```suggestion
  Widget getAnimatedWidget({
    widget,
    required marginTop,```
이걸 의미하신게 맞을까요?

2022-08-30 01:49 UTC, ye-ha commented on lib/main.dart
> +  late final AnimationController _imageAnimationController;
저도 이 부분 고민했어서 좋습니다.👍 애니메이션 코드도 리팩터링하고 싶은 부분이 있어서 코드 수정 후에 말씀하신 방향 대로 적용해보겠습니다.

2022-08-30 02:00 UTC, sebatyler commented on lib/main.dart
> +    required widget,
optional 이 아닌 positional 첫번째로 하자는 의미입니다.

```dart
    Widget getAnimatedWidget(
        widget,
        {
             required ...
        }
    ) {
```

2022-08-30 02:00 UTC, sebatyler commented on lib/main.dart
> +    required widget,
인덴트는 vs code 에서 한게 아니어서 무시해주셔도 좋고요 ㅎㅎ

2022-08-30 02:28 UTC, sebatyler commented on lib/main.dart
> +  late final AnimationController _imageAnimationController;
네 좋습니다!

2022-08-30 10:49 UTC, sebatyler commented on lib/main.dart
> +  late final AnimationController _imageAnimationController;
이 리뷰 외에는 다 바로 적용해서 올려주시고 내일 중으로 애니메이션을 우선 서비스에 적용하는게 어떨까요?

2022-08-31 02:22 UTC, sebatyler commented on lib/main.dart
> +    required widget,
아 이것도 변경하게 되면 여기저기서 수정이 필요하게 되네요
이것도 예하님이 판단해주세요. 이번에 적용할지 말지를요

2022-08-31 05:36 UTC, ye-ha commented on lib/main.dart
> +          ? Positioned(top: imageTop, child: image)
빠뜨린 부분입니다. 😓 반영했습니다. 감사합니다!

2022-08-31 05:36 UTC, ye-ha commented on lib/main.dart
> +  late final AnimationController _imageAnimationController;
네, 알겠습니다 😁

2022-08-31 05:37 UTC, ye-ha commented on lib/main.dart
> +    required widget,
이 부분을 먼저 진행하고 있었어서 이번에 반영하겠습니다. 😁

2022-08-31 05:38 UTC, sebatyler commented on lib/main.dart
> +    required widget,
넵!

2022-08-31 05:38 UTC, ye-ha commented on lib/main.dart
> +      top: pixels <= startingPoint
reverse 값에 따른 부분을 분리했습니다 이해하기 어려운 것같아서 네이밍도 함께 수정했습니다. 계속 고민해볼게요.

2022-08-31 05:58 UTC, ye-ha commented on lib/main.dart
> +                  widget: getDescriptionText(starDescription),
네, 전부 변수로 뺐습니다.

2022-08-31 05:58 UTC, ye-ha commented on lib/main.dart
> +          ...howToPlayPartOne,
오, 말씀해주신 내용으로 변경했습니다 👍

2022-08-31 05:58 UTC, ye-ha commented on lib/main.dart
> +                  widget: getTitleText(suffix: 'NYXS'),
변수로 뺐습니다.

2022-08-31 06:00 UTC, ye-ha commented
리뷰 남겨주신 내용 반영했습니다. 반영이 늦어서 죄송합니다.

2022-08-31 07:15 UTC, sebatyler approved these changes
Confirmed all resolved! Nice work!

2022-08-31 07:17 UTC, merged

2022-09-01 07:58 UTC, ye-ha commented
Thank you for your approval and merge! 😁